// svelte-app/src/routes/players/index.svelte
<style>
  .table {
    text-align: left;
    border-collapse: collapse;
    border-spacing: 0;
    width: 100%;
    font-size: 14px;
  }
  .table .avatar {
    width: 50px;
  }
  .table tr {
    border-bottom: 1px solid #ccc;
  }
  .table .name {
    font-weight: bold;
  }
  .table .tags {
    display: flex;
    align-items: center;
  }
  .table .tags .nation-img,
  .table .tags .league-img {
    width: 24px;
    margin-right: 5px;
  }
  .table .tags .club-img {
    width: 20px;
  }
  .table .rat {
    text-shadow: 0 0 1px #000;
    color: #fff;
    width: 27px;
    height: 27px;
    display: inline-block;
    line-height: 27px;
    border-radius: 4px;
  }
  .table .rat.gold {
    background: linear-gradient(
      45deg,
      #c6a009 0%,
      #f2c40b 50%,
      #f2c40b 51%,
      #f0cf4a 100%
    );
  }
  .table .rat.silver {
    background: linear-gradient(
      45deg,
      #a9aeb1 0%,
      #c2c7ca 50%,
      #c2c7ca 51%,
      #e9ecf0 100%
    );
  }
  .table .rat.bronze {
    background: linear-gradient(
      45deg,
      #6e4c35 0%,
      #9f7f69 50%,
      #9f7f69 51%,
      #ffd9aa 100%
    );
  }
  .table .fixed-width {
    /* width: 50px; */
    text-align: center;
  }
  .table .rat.color90 {
    background: #007e33;
  }
  .table .rat.color80 {
    background: #4caf50;
    color: #fff;
  }
  .table .rat.color70 {
    background: #fbc02d;
    color: #fff;
  }
  .table .rat.color5060 {
    background: #fb8c00;
    color: #fff;
  }
  .table .rat.color40 {
    background: #f44336;
    color: #fff;
  }
</style>

<table class="table">
  <thead>
    <tr>
      <th class="fixed-width" />
      <th>Name</th>
      <th class="fixed-width">RAT</th>
      <th class="fixed-width">POS</th>
      <th class="fixed-width">PAC</th>
      <th class="fixed-width">SHO</th>
      <th class="fixed-width">PAS</th>
      <th class="fixed-width">DRI</th>
      <th class="fixed-width">DEF</th>
      <th class="fixed-width">PHY</th>
      <th class="fixed-width">SKI</th>
      <th class="fixed-width">WF</th>
      <th class="fixed-width">W/R</th>
      <th class="fixed-width">FOOT</th>
      <th class="fixed-width">HEIGHT</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="fixed-width">
        <img
          alt="avatar"
          class="avatar"
          src="https://futhead.cursecdn.com/static/img/20/players/213013.png" />
      </td>
      <td>
        <div class="name">Frank Acheampong</div>
        <div class="tags">
          <img
            alt="nation"
            class="nation-img"
            src="https://futhead.cursecdn.com/static/img/20/nations/21.png" />
          <img
            alt="league"
            class="league-img"
            src="https://futhead.cursecdn.com/static/img/20/leagues/2012.png" />
          <img
            alt="club"
            class="club-img"
            src="https://futhead.cursecdn.com/static/img/20/clubs/111774.png" />
        </div>
      </td>
      <td class="fixed-width">
        <span class="rat bronze">77</span>
      </td>
      <td class="fixed-width">CF</td>
      <td class="fixed-width">
        <span class="rat color90">94</span>
      </td>
      <td class="fixed-width">
        <span class="rat color80">84</span>
      </td>
      <td class="fixed-width">
        <span class="rat color70">74</span>
      </td>
      <td class="fixed-width">
        <span class="rat color5060">55</span>
      </td>
      <td class="fixed-width">
        <span class="rat color40">44</span>
      </td>
      <td class="fixed-width">
        <span class="rat color90">94</span>
      </td>
      <td class="fixed-width">4*</td>
      <td class="fixed-width">3*</td>
      <td class="fixed-width">H / L</td>
      <td class="fixed-width">R</td>
      <td class="fixed-width">168cm</td>
    </tr>
  </tbody>
</table>

// react-app/src/pages/Players/Players.js
import React from 'react';
import css from './Players.module.scss';

const Players = props => {
  return (
    <table className={css.table}>
      <thead>
        <tr>
          <th className={css.fixed}></th>
          <th>Name</th>
          <th className={css.fixed}>RAT</th>
          <th className={css.fixed}>POS</th>
          <th className={css.fixed}>PAC</th>
          <th className={css.fixed}>SHO</th>
          <th className={css.fixed}>PAS</th>
          <th className={css.fixed}>DRI</th>
          <th className={css.fixed}>DEF</th>
          <th className={css.fixed}>PHY</th>
          <th className={css.fixed}>SKI</th>
          <th className={css.fixed}>WF</th>
          <th className={css.fixed}>W/R</th>
          <th className={css.fixed}>FOOT</th>
          <th className={css.fixed}>HEIGHT</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td className={css.fixed}>
            <img
              alt="avatar"
              className={css.avatar}
              src="https://futhead.cursecdn.com/static/img/20/players/213013.png"
            />
          </td>
          <td>
            <div className={css.name}>Frank Acheampong</div>
            <div className={css.tags}>
              <img
                alt="nation"
                className={css.nationImg}
                src="https://futhead.cursecdn.com/static/img/20/nations/21.png"
              />
              <img
                alt="league"
                className={css.leagueImg}
                src="https://futhead.cursecdn.com/static/img/20/leagues/2012.png"
              />
              <img
                alt="club"
                className={css.clubImg}
                src="https://futhead.cursecdn.com/static/img/20/clubs/111774.png"
              />
            </div>
          </td>
          <td className={css.fixed}>
            <span className={[css.rat, css.bronze].join(' ')}>77</span>
          </td>
          <td className={css.fixed}>CF</td>
          <td className={css.fixed}>
            <span className={[css.rat, css.color90].join(' ')}>94</span>
          </td>
          <td className={css.fixed}>
            <span className={[css.rat, css.color80].join(' ')}>84</span>
          </td>
          <td className={css.fixed}>
            <span className={[css.rat, css.color70].join(' ')}>74</span>
          </td>
          <td className={css.fixed}>
            <span className={[css.rat, css.color5060].join(' ')}>55</span>
          </td>
          <td className={css.fixed}>
            <span className={[css.rat, css.color40].join(' ')}>44</span>
          </td>
          <td className={css.fixed}>
            <span className={[css.rat, css.color90].join(' ')}>94</span>
          </td>
          <td className={css.fixed}>4*</td>
          <td className={css.fixed}>3*</td>
          <td className={css.fixed}>H / L</td>
          <td className={css.fixed}>R</td>
          <td className={css.fixed}>168cm</td>
        </tr>
      </tbody>
    </table>
  );
};

export default Players;
